language: node_js
node_js:
  - '5'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - URL: dojocon.coderdojo.jp
    - GIT_USER: Travis CI
    - GIT_EMAIL: ixkaito@gmail.com
    - GITHUB_RELEASE_REPO: 'ixkaito/travis-deploy-test-release'
    - RELEASE_BRANCH: &release_branch release

branches:
  only:
    - master
    - *release_branch

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - pwd
  - bash ./deploy.sh

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$RELEASE_BRANCH" ]; then exit 0; fi

sudo: false
