language: node_js
node_js:
  - '5'

branches:
  only:
    - master
    - release

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GITHUB_RELEASE_REPO: 'ixkaito/travis-deploy-test-release'

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "release" ]; then exit 0; fi
  - git push -f -q "https://${GITHUB_TOKEN}@github.com/${GITHUB_RELEASE_REPO}.git" release:gh-pages > /dev/null 2>&1

sudo: false
